{
  "formatVersion": "1.1",
  "component": {
    "group": "ca.team4308",
    "module": "absolutelib-java",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "absolutelib-java-1.0.5.jar",
          "url": "absolutelib-java-1.0.5.jar",
          "size": 110963,
          "sha512": "24bca5d8bc3f8203ab36eb0bf8404a940d5381ffee7335ddae9c656bcc729a2888f36cc498454d1db58207bdd88ec840cdc21e9c34bc65ac79bca4478f7563a8",
          "sha256": "8e7f71a9738cba9348bf87a98e8cb714b7103dacc346c5d4e0f0a6492b196d9b",
          "sha1": "15ee6e547d20332f65cb048b5c6c49db95cb42de",
          "md5": "ac7d09116f5e3529098316642f4615b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2025.+"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2025.+"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2025.+"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2025.+"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2025.+"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2025.+"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2025.+"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2025.+"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2025.+"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-2"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "api-java",
          "version": {
            "requires": "5.33.1"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "wpiapi-java",
          "version": {
            "requires": "5.33.1"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "25.4.0"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2025.0.0"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.43.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.13.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.littletonrobotics.akit",
          "module": "akit-java",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.pathplanner.lib",
          "module": "PathplannerLib-java",
          "version": {
            "requires": "2025.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "absolutelib-java-1.0.5.jar",
          "url": "absolutelib-java-1.0.5.jar",
          "size": 110963,
          "sha512": "24bca5d8bc3f8203ab36eb0bf8404a940d5381ffee7335ddae9c656bcc729a2888f36cc498454d1db58207bdd88ec840cdc21e9c34bc65ac79bca4478f7563a8",
          "sha256": "8e7f71a9738cba9348bf87a98e8cb714b7103dacc346c5d4e0f0a6492b196d9b",
          "sha1": "15ee6e547d20332f65cb048b5c6c49db95cb42de",
          "md5": "ac7d09116f5e3529098316642f4615b7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "absolutelib-java-1.0.5-sources.jar",
          "url": "absolutelib-java-1.0.5-sources.jar",
          "size": 55192,
          "sha512": "079dcc7d4b662ae491422e79d2ce9b0d3aff8af0edfd0c6a725c6276edf2f4bd74320fae0e73ecfaf255e579f2c87c6d6a9f150eabf7398aea06205188116c78",
          "sha256": "8d92756c47dcb41f2fb0ec8ecd3dc824b96219d35a51ac17fff849d610c3ac8a",
          "sha1": "5afd2ae6deecba352c93286e68eb740a1edd827e",
          "md5": "e02d98e8876e0df1bee66a35ec2e078d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "absolutelib-java-1.0.5-javadoc.jar",
          "url": "absolutelib-java-1.0.5-javadoc.jar",
          "size": 351124,
          "sha512": "6f3456924b112f8f1d4d2992e5fdf290e7bce546e083e1d1b89c46691f9f23c9119a615d686514fc7c031f509586fb609fc2ac335414e9832321499d396c0f54",
          "sha256": "02d15b2c93efe80b403bf78f0b1e6bd01a422934a19335b7de875b6b6abb1a7b",
          "sha1": "5c4fdf69f55ec5ce4c383706c923c8f637651f29",
          "md5": "eab150724652affa18e2088273ce041c"
        }
      ]
    }
  ]
}
