{
  "formatVersion": "1.1",
  "component": {
    "group": "ca.team4308",
    "module": "absolutelib-java",
    "version": "1.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "absolutelib-java-1.2.6.jar",
          "url": "absolutelib-java-1.2.6.jar",
          "size": 226495,
          "sha512": "979bbc6259dfe5a8cecee7fc29a31be6ea3cd1b823ab573f39451f5d6d47f97b0c26dd46a71f6c2e898deffff90c70b8a14a26fe99dd2a51af7eb3e1b237dfc5",
          "sha256": "c820c93cc539065fa42416d7899f0749d58b704b7fd2d268eb714a93a717ded7",
          "sha1": "a83ef201680284287176661350d129cc0ce53cba",
          "md5": "47cd31566f7a7d6b527c571a04c4d335"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "api-java",
          "version": {
            "requires": "5.36.0"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "wpiapi-java",
          "version": {
            "requires": "5.36.0"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "26.1.0"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2026.0.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.littletonrobotics.akit",
          "module": "akit-java",
          "version": {
            "requires": "26.0.0"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.pathplanner.lib",
          "module": "PathplannerLib-java",
          "version": {
            "requires": "2026.1.2"
          }
        },
        {
          "group": "org.photonvision",
          "module": "photonlib-java",
          "version": {
            "requires": "v2026.1.1-rc-3"
          }
        },
        {
          "group": "org.photonvision",
          "module": "photontargeting-java",
          "version": {
            "requires": "v2026.1.1-rc-3"
          }
        },
        {
          "group": "swervelib",
          "module": "YAGSL-java",
          "version": {
            "requires": "2026.1.14"
          }
        }
      ],
      "files": [
        {
          "name": "absolutelib-java-1.2.6.jar",
          "url": "absolutelib-java-1.2.6.jar",
          "size": 226495,
          "sha512": "979bbc6259dfe5a8cecee7fc29a31be6ea3cd1b823ab573f39451f5d6d47f97b0c26dd46a71f6c2e898deffff90c70b8a14a26fe99dd2a51af7eb3e1b237dfc5",
          "sha256": "c820c93cc539065fa42416d7899f0749d58b704b7fd2d268eb714a93a717ded7",
          "sha1": "a83ef201680284287176661350d129cc0ce53cba",
          "md5": "47cd31566f7a7d6b527c571a04c4d335"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "absolutelib-java-1.2.6-sources.jar",
          "url": "absolutelib-java-1.2.6-sources.jar",
          "size": 114063,
          "sha512": "975498671da83afd4c4eeaab1b7bad786c542182f3735b660cd9a6ca7f0801edf40aca353a404e8edd84a1540e453ede329834de3f6d1ba469b701b5461bac1f",
          "sha256": "bf7bd9917405fbc9ee1a4207211890ab5907bc51941d9c710a314a00fc89b1b7",
          "sha1": "31733a6a45b651d5510cce8900b73f03f16f5bf5",
          "md5": "5a17b7ec64350ed31d3a271c64282009"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "absolutelib-java-1.2.6-javadoc.jar",
          "url": "absolutelib-java-1.2.6-javadoc.jar",
          "size": 573528,
          "sha512": "a64efe9522cc2315440d417d1c286826c3615fd254992dc97b31f3ed143b8b16810acff340a105c34e72dacc09fb7c0ff958b0100ac90d4a4bba18223d57f953",
          "sha256": "9d0982ba26e1b78dd02563ba8916488e539f73dc83369105bb2b3f7a8fe696c4",
          "sha1": "47176bba41f6700e6866fa5e81f223779dde8679",
          "md5": "ad8cf4fdb7af502a091b3c24175c4b9b"
        }
      ]
    }
  ]
}
