{
  "formatVersion": "1.1",
  "component": {
    "group": "ca.team4308",
    "module": "absolutelib-java",
    "version": "1.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "absolutelib-java-1.2.9.jar",
          "url": "absolutelib-java-1.2.9.jar",
          "size": 245652,
          "sha512": "3deaf6e8f9a01c9e51ccedf9155afa4c52f5ebb19e582a9cfd9e19ac4fa52ebc54c8429a095e0f7834ffe3bc988f16041fced67d57ee3cfe4b12f8425ffee9b7",
          "sha256": "2695d7143fc807f5a92c268472283bfe49a88358f838ac0c8857347cf8197bd1",
          "sha1": "7d1a863004ebe9977b26f9b87a503e9c6421ec08",
          "md5": "0276d8ca76a5c3e8deb92474bc7f8716"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "api-java",
          "version": {
            "requires": "5.36.0"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "wpiapi-java",
          "version": {
            "requires": "5.36.0"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "26.1.0"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2026.0.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.littletonrobotics.akit",
          "module": "akit-java",
          "version": {
            "requires": "26.0.0"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.pathplanner.lib",
          "module": "PathplannerLib-java",
          "version": {
            "requires": "2026.1.2"
          }
        },
        {
          "group": "org.photonvision",
          "module": "photonlib-java",
          "version": {
            "requires": "v2026.1.1-rc-3"
          }
        },
        {
          "group": "org.photonvision",
          "module": "photontargeting-java",
          "version": {
            "requires": "v2026.1.1-rc-3"
          }
        },
        {
          "group": "swervelib",
          "module": "YAGSL-java",
          "version": {
            "requires": "2026.1.14"
          }
        }
      ],
      "files": [
        {
          "name": "absolutelib-java-1.2.9.jar",
          "url": "absolutelib-java-1.2.9.jar",
          "size": 245652,
          "sha512": "3deaf6e8f9a01c9e51ccedf9155afa4c52f5ebb19e582a9cfd9e19ac4fa52ebc54c8429a095e0f7834ffe3bc988f16041fced67d57ee3cfe4b12f8425ffee9b7",
          "sha256": "2695d7143fc807f5a92c268472283bfe49a88358f838ac0c8857347cf8197bd1",
          "sha1": "7d1a863004ebe9977b26f9b87a503e9c6421ec08",
          "md5": "0276d8ca76a5c3e8deb92474bc7f8716"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "absolutelib-java-1.2.9-sources.jar",
          "url": "absolutelib-java-1.2.9-sources.jar",
          "size": 127929,
          "sha512": "3eb091a7115e52e8e516c52e2b68784b253822f342966c3cf7dde1e624107d35984efb4bfdd93418c86cec2b8aa5dfc4879ae1c7a997bb4e27bc758360d682ad",
          "sha256": "c3103de165cdabc4de2dfde043b4bc9f3600cbf367f44bd93a40b8fe72f0a74c",
          "sha1": "099a73a1bb6e25dedb4bf1fe0f996049d30af976",
          "md5": "d218a922aa4b5277bc3a0fb0fd0aa14f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "absolutelib-java-1.2.9-javadoc.jar",
          "url": "absolutelib-java-1.2.9-javadoc.jar",
          "size": 595078,
          "sha512": "8562994dfcf7486d0984f0e8267507ccac9c609ba854e04bc79f70f9e05ad46d73a887015400b93abacaafddd75a0138251247549d17d1a78cc03a0176266bb3",
          "sha256": "3a9cccf87c883a9b303daf2238390d4932f1329b26e83655f505ee11b80fd706",
          "sha1": "37fb085b820ef3f2a8d78d5f8fe1f28ed02563da",
          "md5": "66e63ea3665228462af7cf688ef1b6e1"
        }
      ]
    }
  ]
}
