{
  "formatVersion": "1.1",
  "component": {
    "group": "ca.team4308",
    "module": "absolutelib-java",
    "version": "1.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "absolutelib-java-1.2.3.jar",
          "url": "absolutelib-java-1.2.3.jar",
          "size": 139108,
          "sha512": "61db30498eb8b8ec59cbac98c62d07397bd86cba3ca50349f32d7b006de7d327b13f869b2ef6ce70b5fb4a1e77ffb1719c2026ae8e2d97c764a73678e047fad8",
          "sha256": "38f5fd031a466d4d09653d1713618ea5391375e23e80a8725b8955db864a7cef",
          "sha1": "31e9000c4c9782b174a4a6c73697559d551caf66",
          "md5": "d91b0c59d49e99b73aab46c7a508bdcb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "api-java",
          "version": {
            "requires": "5.36.0"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "wpiapi-java",
          "version": {
            "requires": "5.36.0"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "26.1.0"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2026.0.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.littletonrobotics.akit",
          "module": "akit-java",
          "version": {
            "requires": "26.0.0"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.pathplanner.lib",
          "module": "PathplannerLib-java",
          "version": {
            "requires": "2026.1.2"
          }
        },
        {
          "group": "org.photonvision",
          "module": "photonlib-java",
          "version": {
            "requires": "v2026.1.1-rc-3"
          }
        },
        {
          "group": "org.photonvision",
          "module": "photontargeting-java",
          "version": {
            "requires": "v2026.1.1-rc-3"
          }
        },
        {
          "group": "swervelib",
          "module": "YAGSL-java",
          "version": {
            "requires": "2026.1.14"
          }
        }
      ],
      "files": [
        {
          "name": "absolutelib-java-1.2.3.jar",
          "url": "absolutelib-java-1.2.3.jar",
          "size": 139108,
          "sha512": "61db30498eb8b8ec59cbac98c62d07397bd86cba3ca50349f32d7b006de7d327b13f869b2ef6ce70b5fb4a1e77ffb1719c2026ae8e2d97c764a73678e047fad8",
          "sha256": "38f5fd031a466d4d09653d1713618ea5391375e23e80a8725b8955db864a7cef",
          "sha1": "31e9000c4c9782b174a4a6c73697559d551caf66",
          "md5": "d91b0c59d49e99b73aab46c7a508bdcb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "absolutelib-java-1.2.3-sources.jar",
          "url": "absolutelib-java-1.2.3-sources.jar",
          "size": 65324,
          "sha512": "2f0ca8f9747e42e502aa34f1e93a0a873d46022f8a05e266663f85c2ab2d5db00d1854308cc90abc5342d0051001044d61eaf50d960fc56723cb0248f18f435e",
          "sha256": "042b122cf30bff7faf2c0979e20ea0893e8cb05fbd3aad7b483c267524a05896",
          "sha1": "f19e41c8b0561d297943122c5eeded788870bda8",
          "md5": "32bfc5551abc766bbb10ce0f4c0eb6ff"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "absolutelib-java-1.2.3-javadoc.jar",
          "url": "absolutelib-java-1.2.3-javadoc.jar",
          "size": 380823,
          "sha512": "cda07c0757f1078bb8f1d599fc47f0af3552e6a0924a9842dc55e2c0e9b01fe448454a9e67a5a4f3ab5eed73737b252e1c2933df7a2bdda3fc893356eecdd100",
          "sha256": "0415fb9bd9cfc8f17a040f566c28618beb5924972d4c1241301c62af492cd015",
          "sha1": "5cddfa99f7b1954d574116f8832bd153ea022971",
          "md5": "add692184e79f3b643f4565853f264f5"
        }
      ]
    }
  ]
}
