{
  "formatVersion": "1.1",
  "component": {
    "group": "ca.team4308",
    "module": "absolutelib-java",
    "version": "1.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "absolutelib-java-1.2.8.jar",
          "url": "absolutelib-java-1.2.8.jar",
          "size": 231315,
          "sha512": "1eb369766dc82ea2846ca6ccca6cdd7b5a76c0abcc887c7f520486b1d80ca95e61f4aac3bdf1b70202c85a991756e83ef870009b5b91c815d98d56fe5e0aa672",
          "sha256": "a3e93a2ecbeb98b2539250bc5b2e4868a1591b744fa53dc78ab5ced6550d35e3",
          "sha1": "46e4609587ea86cc3b95947c8c18f9ed22faa52f",
          "md5": "27929acf14671a3c4170fd7c039cce72"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "api-java",
          "version": {
            "requires": "5.36.0"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "wpiapi-java",
          "version": {
            "requires": "5.36.0"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "26.1.0"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2026.0.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.littletonrobotics.akit",
          "module": "akit-java",
          "version": {
            "requires": "26.0.0"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.pathplanner.lib",
          "module": "PathplannerLib-java",
          "version": {
            "requires": "2026.1.2"
          }
        },
        {
          "group": "org.photonvision",
          "module": "photonlib-java",
          "version": {
            "requires": "v2026.1.1-rc-3"
          }
        },
        {
          "group": "org.photonvision",
          "module": "photontargeting-java",
          "version": {
            "requires": "v2026.1.1-rc-3"
          }
        },
        {
          "group": "swervelib",
          "module": "YAGSL-java",
          "version": {
            "requires": "2026.1.14"
          }
        }
      ],
      "files": [
        {
          "name": "absolutelib-java-1.2.8.jar",
          "url": "absolutelib-java-1.2.8.jar",
          "size": 231315,
          "sha512": "1eb369766dc82ea2846ca6ccca6cdd7b5a76c0abcc887c7f520486b1d80ca95e61f4aac3bdf1b70202c85a991756e83ef870009b5b91c815d98d56fe5e0aa672",
          "sha256": "a3e93a2ecbeb98b2539250bc5b2e4868a1591b744fa53dc78ab5ced6550d35e3",
          "sha1": "46e4609587ea86cc3b95947c8c18f9ed22faa52f",
          "md5": "27929acf14671a3c4170fd7c039cce72"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "absolutelib-java-1.2.8-sources.jar",
          "url": "absolutelib-java-1.2.8-sources.jar",
          "size": 119274,
          "sha512": "4821dc3a174213862801b6778505a74e28346d9487b7e93ccf88a254f7fbba02e53504af40504d634ed14b31db326a59b8d7a8444ebf5a5d9f7b486c34ab960d",
          "sha256": "8a28dffff72cf03d4b1d97e6b077826b94dc09aa83e71688f07c3560f66ad910",
          "sha1": "6804d01f5f137ebaf84ea871764f936585ffc407",
          "md5": "f30b3c2a7b4a90440d9eea894d3f25c4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "absolutelib-java-1.2.8-javadoc.jar",
          "url": "absolutelib-java-1.2.8-javadoc.jar",
          "size": 582811,
          "sha512": "a1e752e9ea6d0623bdb5fb3b2a7f6a2857178d62e03a763fd214e8b7c396bf6d17ac6a7468ed233b5f7fb6c563c86a9990d8defdfc6c0e963c3394089037a311",
          "sha256": "f49b4ff866af395b0d095b6e1d672f83da4d5e9a72e2a34c5e119418d8990bc5",
          "sha1": "3a0299cee7ad2a6f34d9b7f44c07260fcfc9e8cd",
          "md5": "88245dbbda2831f2baca9c60c51f8474"
        }
      ]
    }
  ]
}
