{
  "formatVersion": "1.1",
  "component": {
    "group": "ca.team4308",
    "module": "absolutelib-java",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "absolutelib-java-1.1.3.jar",
          "url": "absolutelib-java-1.1.3.jar",
          "size": 122934,
          "sha512": "1a8bb8f5f7a02ca357e520f54f33d9ddd75208122fbf3c9e102e9bdea1acba9fd3fbb147cda16a8289bdfbabb15159be070c3183deec90888d1f695db9e0c229",
          "sha256": "cbae506e53a6f55fb298fd8ca729d86687b7db50910ec36f642dee36060884a5",
          "sha1": "688556da3d05d31994f7463567de9db6c1516269",
          "md5": "b4f60a2743025ea3404bb111c66fb814"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "api-java",
          "version": {
            "requires": "5.33.1"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "wpiapi-java",
          "version": {
            "requires": "5.33.1"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "25.4.0"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2025.0.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.littletonrobotics.akit",
          "module": "akit-java",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.pathplanner.lib",
          "module": "PathplannerLib-java",
          "version": {
            "requires": "2025.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "absolutelib-java-1.1.3.jar",
          "url": "absolutelib-java-1.1.3.jar",
          "size": 122934,
          "sha512": "1a8bb8f5f7a02ca357e520f54f33d9ddd75208122fbf3c9e102e9bdea1acba9fd3fbb147cda16a8289bdfbabb15159be070c3183deec90888d1f695db9e0c229",
          "sha256": "cbae506e53a6f55fb298fd8ca729d86687b7db50910ec36f642dee36060884a5",
          "sha1": "688556da3d05d31994f7463567de9db6c1516269",
          "md5": "b4f60a2743025ea3404bb111c66fb814"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "absolutelib-java-1.1.3-sources.jar",
          "url": "absolutelib-java-1.1.3-sources.jar",
          "size": 60818,
          "sha512": "4b54b7f46d6661736dcdb8f0cd74f9f6e548728aade9864089324992e6ea459eec268ea54c75b9269c56618fe5ee4a386e82fb50f77964b5b3534818379d4ad5",
          "sha256": "2ff555d679a028c50126b51e5089654bbe981e44b1302f59c08fc28268092655",
          "sha1": "d0cc9812f7a0be0cd62f85a9b86e23f6ae6a55a3",
          "md5": "ae28911190b9a5b2e7d3670625f08843"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "absolutelib-java-1.1.3-javadoc.jar",
          "url": "absolutelib-java-1.1.3-javadoc.jar",
          "size": 377376,
          "sha512": "60afea747af7083b31d726044ee975a98bb0e5a7febc0b26b58e5f74f2645a6bc340c827e79d23b46cf15905c2b3b360d894e7be1245baca37ea2ef7069e9873",
          "sha256": "c9d6d857538bfaaeed76cbfdec8e70aa38094d5edba1f79e9e6240c2ce07d929",
          "sha1": "8b887577a404ae47853c47e7cc81b74ae0736c93",
          "md5": "bf930da2ea5f968bcca5b06e4ce47888"
        }
      ]
    }
  ]
}
