{
  "formatVersion": "1.1",
  "component": {
    "group": "ca.team4308",
    "module": "absolutelib-java",
    "version": "2.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "absolutelib-java-2.2.5.jar",
          "url": "absolutelib-java-2.2.5.jar",
          "size": 759571,
          "sha512": "96eda45bcd50a7f3ecfec5185d7c23d8cd99fa407b52fab5709e6c3023cdfbee380d561c4f710f47bfab7a3314d9b7180ce3e3931fe9a0ba30de6778c893ed06",
          "sha256": "9074b99d8b202f77672a140ce41217f8fac0e5c5477872bf1057765294a8fced",
          "sha1": "4b3b16081dd845cb0a717707f31be60a28a7a4f0",
          "md5": "9b530a415679911c3825adfdfc63c8fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "api-java",
          "version": {
            "requires": "5.36.0"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "wpiapi-java",
          "version": {
            "requires": "5.36.0"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "26.1.0"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2026.0.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.littletonrobotics.akit",
          "module": "akit-java",
          "version": {
            "requires": "26.0.0"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.pathplanner.lib",
          "module": "PathplannerLib-java",
          "version": {
            "requires": "2026.1.2"
          }
        },
        {
          "group": "org.photonvision",
          "module": "photonlib-java",
          "version": {
            "requires": "v2026.1.1-rc-3"
          }
        },
        {
          "group": "org.photonvision",
          "module": "photontargeting-java",
          "version": {
            "requires": "v2026.1.1-rc-3"
          }
        },
        {
          "group": "swervelib",
          "module": "YAGSL-java",
          "version": {
            "requires": "2026.1.14"
          }
        }
      ],
      "files": [
        {
          "name": "absolutelib-java-2.2.5.jar",
          "url": "absolutelib-java-2.2.5.jar",
          "size": 759571,
          "sha512": "96eda45bcd50a7f3ecfec5185d7c23d8cd99fa407b52fab5709e6c3023cdfbee380d561c4f710f47bfab7a3314d9b7180ce3e3931fe9a0ba30de6778c893ed06",
          "sha256": "9074b99d8b202f77672a140ce41217f8fac0e5c5477872bf1057765294a8fced",
          "sha1": "4b3b16081dd845cb0a717707f31be60a28a7a4f0",
          "md5": "9b530a415679911c3825adfdfc63c8fa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "absolutelib-java-2.2.5-sources.jar",
          "url": "absolutelib-java-2.2.5-sources.jar",
          "size": 598074,
          "sha512": "ea6e61f807ed67033e1f9b962295ae53f12eab12d34307629adf006b1365faf9e105ff304f949216dd97c806b322c7391625b79deb25142eef71f66c9ad2a81b",
          "sha256": "8c94fdec811a4b79022a91011fbcedd43aab3f2ea238f091c76b4ad3873437df",
          "sha1": "4a459b47e795a7700976dbb33e261c0d41bc20a2",
          "md5": "b3bac34a3bf06487e1e59c385ced0f37"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "absolutelib-java-2.2.5-javadoc.jar",
          "url": "absolutelib-java-2.2.5-javadoc.jar",
          "size": 836591,
          "sha512": "20ab97866985e2c45a9d7d8fc39a2cb6fa37655a8511c0851f108de92c64388c538e2097cd643c6595b4add135ce3d8fb668a3b5950580f8e695fa0a4e482cbf",
          "sha256": "85f38d030fd44c069c119a2d36857f1474b4a061caf91f7268259b845ac1d804",
          "sha1": "76a0d9c1b3fcfe9f3458f7bf0bb16a7ff9bde6ec",
          "md5": "b8c713d58f921f826a1363b5068842be"
        }
      ]
    }
  ]
}
