{
  "formatVersion": "1.1",
  "component": {
    "group": "ca.team4308",
    "module": "absolutelib-java",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "absolutelib-java-1.2.0.jar",
          "url": "absolutelib-java-1.2.0.jar",
          "size": 140991,
          "sha512": "4a2aca7b2a1c47e908f2913c0cb3598b087ddbbc63732c71ad038ff080186e6bc56d5fd0321560a325b06415c2aedc9cf48e72e219b5005436c1292d3267b963",
          "sha256": "69e17e4b5ad0e2cb9c171275f8b8ae0a8337dc5680e6f4e57e20a3c9b1e41b8c",
          "sha1": "f8e7310fc9aec5988848a10c2f7e82a9d65fe987",
          "md5": "de1eef6a00be6c322700921e5175f337"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "api-java",
          "version": {
            "requires": "5.33.1"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "wpiapi-java",
          "version": {
            "requires": "5.33.1"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "25.4.0"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2025.0.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.littletonrobotics.akit",
          "module": "akit-java",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.pathplanner.lib",
          "module": "PathplannerLib-java",
          "version": {
            "requires": "2025.2.7"
          }
        },
        {
          "group": "org.photonvision",
          "module": "photonlib-java",
          "version": {
            "requires": "v2025.3.1-rc3"
          }
        },
        {
          "group": "org.photonvision",
          "module": "photontargeting-java",
          "version": {
            "requires": "v2025.3.1-rc3"
          }
        },
        {
          "group": "swervelib",
          "module": "YAGSL-java",
          "version": {
            "requires": "2025.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "absolutelib-java-1.2.0.jar",
          "url": "absolutelib-java-1.2.0.jar",
          "size": 140991,
          "sha512": "4a2aca7b2a1c47e908f2913c0cb3598b087ddbbc63732c71ad038ff080186e6bc56d5fd0321560a325b06415c2aedc9cf48e72e219b5005436c1292d3267b963",
          "sha256": "69e17e4b5ad0e2cb9c171275f8b8ae0a8337dc5680e6f4e57e20a3c9b1e41b8c",
          "sha1": "f8e7310fc9aec5988848a10c2f7e82a9d65fe987",
          "md5": "de1eef6a00be6c322700921e5175f337"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "absolutelib-java-1.2.0-sources.jar",
          "url": "absolutelib-java-1.2.0-sources.jar",
          "size": 67642,
          "sha512": "651dc95e961cacc2128096d6e56408bedc20561aa6c99dc73317382bf7885cc0d190199305b58f660cb2d484ace0e3bf9278ba4679c824c14066496018a669b8",
          "sha256": "fd5e1c068fee7e4a15779116a73fc192d6d74feb927fc6d02433f37fb6600b02",
          "sha1": "27913133a2e5f007b00824dec68f5d333227d438",
          "md5": "61e10a62df75d7eaab746575b6b89f93"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "absolutelib-java-1.2.0-javadoc.jar",
          "url": "absolutelib-java-1.2.0-javadoc.jar",
          "size": 394730,
          "sha512": "5e98bca512c787cb5279972ea5baf26c95e2ee15e3ee7ba7e531a2c2a0cb1abbc12db9fa677eeca1752d40afd28d4d40736bbcb454f2b9a3d1377fb50c409e5b",
          "sha256": "e22ba0e56d00164e6de6ee49e13194721b5fb4e72cf2814b31fc1025fbc139ec",
          "sha1": "6e02ab853febbfcd5e68a8efe79781063635808c",
          "md5": "b8853f738439aea42f633d4cae45cfb6"
        }
      ]
    }
  ]
}
