plugins {
    id 'java'
    id 'com.gradleup.shadow' version '8.3.3'
    id 'edu.wpi.first.wpilib.repositories.WPILibRepositoriesPlugin' version '2025.0'
    
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

ext.wpilibVersion = "2026.1.1"

repositories {
    mavenLocal()
    mavenCentral()
    maven { url = uri("https://maven.ctr-electronics.com/release/") } // CTRE
    maven { url = uri("https://maven.revrobotics.com/") } // REV
    maven { url = uri("https://maven.photonvision.org/repository/release/") } // PhotonVision
    maven { url = uri("https://3015rangerrobotics.github.io/pathplannerlib/repo") } // PathPlanner
    maven { url = uri("https://frcmaven.wpi.edu/release") } // WPILib fallback
    maven { url = uri("https://frcmaven.wpi.edu/artifactory/littletonrobotics-mvn-release/") } // AdvantageKit
    maven { url = uri("https://maven.photonvision.org/repository/internal") } // Photon Vision
    maven { url = uri("https://maven.photonvision.org/repository/snapshots") }
    maven { url = uri("https://yet-another-software-suite.github.io/YAGSL/releases/") } // YAGSL
}


dependencies {
    implementation project(':')
    
    // WPILib bindings
    implementation "edu.wpi.first.cscore:cscore-java:$wpilibVersion"
    implementation "edu.wpi.first.cameraserver:cameraserver-java:$wpilibVersion"
    implementation "edu.wpi.first.ntcore:ntcore-java:$wpilibVersion"
    implementation "edu.wpi.first.wpilibj:wpilibj-java:$wpilibVersion"
    implementation "edu.wpi.first.wpilibNewCommands:wpilibNewCommands-java:$wpilibVersion"
    implementation "edu.wpi.first.wpimath:wpimath-java:$wpilibVersion"
    implementation "edu.wpi.first.hal:hal-java:$wpilibVersion"
    implementation "edu.wpi.first.wpiutil:wpiutil-java:$wpilibVersion"
    implementation "edu.wpi.first.wpiunits:wpiunits-java:$wpilibVersion"
    implementation "edu.wpi.first.apriltag:apriltag-java:$wpilibVersion"
    // HTTP/JSON
    implementation 'io.javalin:javalin:6.1.3'
    implementation 'org.slf4j:slf4j-simple:2.0.11'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.2'
}

configurations {
    nativeZips
}

dependencies {
    def platforms = ['windowsx86-64', 'linuxx86-64', 'linuxarm64']
    platforms.each { platform ->
        nativeZips "edu.wpi.first.ntcore:ntcore-cpp:$wpilibVersion:${platform}@zip"
        nativeZips "edu.wpi.first.hal:hal-cpp:$wpilibVersion:${platform}@zip"
        nativeZips "edu.wpi.first.wpimath:wpimath-cpp:$wpilibVersion:${platform}@zip"
        nativeZips "edu.wpi.first.cscore:cscore-cpp:$wpilibVersion:${platform}@zip"
        nativeZips "edu.wpi.first.apriltag:apriltag-cpp:$wpilibVersion:${platform}@zip"
        nativeZips "edu.wpi.first.wpiutil:wpiutil-cpp:$wpilibVersion:${platform}@zip"
        nativeZips "edu.wpi.first.wpinet:wpinet-cpp:$wpilibVersion:${platform}@zip"
    }
}

jar {
    manifest {
        attributes 'Main-Class': 'ca.team4308.coprocessor.Main'
    }
}

task extractNatives(type: Sync) {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    from({ project.configurations.nativeZips.collect { zipTree(it) } }) {
        include '**/*.dll'
        include '**/*.so'
        include '**/*.dylib'
        eachFile { fcd ->
            def segments = fcd.relativePath.segments
            def newSegments = segments.findAll { it != 'shared' }
            fcd.relativePath = new RelativePath(true, newSegments as String[])
        }
        includeEmptyDirs = false
    }
    into layout.buildDirectory.dir("natives")
}

shadowJar {
    dependsOn extractNatives
    archiveBaseName.set('coprocessor')
    archiveClassifier.set('')
    archiveVersion.set('')
}
