{
  "formatVersion": "1.1",
  "component": {
    "group": "ca.team4308",
    "module": "absolutelib-java",
    "version": "1.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "absolutelib-java-1.2.7.jar",
          "url": "absolutelib-java-1.2.7.jar",
          "size": 226922,
          "sha512": "4de4cbae6c0c28c4e8a7a32b320e59415fb00aa0b96ef2ef2a4b652b9ffb0f3def2dc9a6e7e8e4d0d8448597d6b71f615b7b3f0f27d140bbdc84be262755f5da",
          "sha256": "7ba54ce76aedfd045e30c97b5b918e5028d51aeb89b8ffec7d0d22a5b06f5ba6",
          "sha1": "ec4ed6c561a828211530ce0f7dda0989b6b159f9",
          "md5": "121e055326e8e1b368a35dc9db2118c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "api-java",
          "version": {
            "requires": "5.36.0"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "wpiapi-java",
          "version": {
            "requires": "5.36.0"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "26.1.0"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2026.0.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.littletonrobotics.akit",
          "module": "akit-java",
          "version": {
            "requires": "26.0.0"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.pathplanner.lib",
          "module": "PathplannerLib-java",
          "version": {
            "requires": "2026.1.2"
          }
        },
        {
          "group": "org.photonvision",
          "module": "photonlib-java",
          "version": {
            "requires": "v2026.1.1-rc-3"
          }
        },
        {
          "group": "org.photonvision",
          "module": "photontargeting-java",
          "version": {
            "requires": "v2026.1.1-rc-3"
          }
        },
        {
          "group": "swervelib",
          "module": "YAGSL-java",
          "version": {
            "requires": "2026.1.14"
          }
        }
      ],
      "files": [
        {
          "name": "absolutelib-java-1.2.7.jar",
          "url": "absolutelib-java-1.2.7.jar",
          "size": 226922,
          "sha512": "4de4cbae6c0c28c4e8a7a32b320e59415fb00aa0b96ef2ef2a4b652b9ffb0f3def2dc9a6e7e8e4d0d8448597d6b71f615b7b3f0f27d140bbdc84be262755f5da",
          "sha256": "7ba54ce76aedfd045e30c97b5b918e5028d51aeb89b8ffec7d0d22a5b06f5ba6",
          "sha1": "ec4ed6c561a828211530ce0f7dda0989b6b159f9",
          "md5": "121e055326e8e1b368a35dc9db2118c4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "absolutelib-java-1.2.7-sources.jar",
          "url": "absolutelib-java-1.2.7-sources.jar",
          "size": 114594,
          "sha512": "ea69c0ebd95a5eb12ab0e3219519177a829ab79ab2c0ac65e64db8d14447cd3d8c1de5d26a950ba9fcc9860ede0d245af742b5101396992d0f93881b1559642d",
          "sha256": "623d942f601d70d29beae5ea77b4a6ee558fce2e90664f8d1575038732287b41",
          "sha1": "c851ebd6cea11be11c38bf3c244983c23c39cd27",
          "md5": "5deb06f71d0ed43bf6023bd7c0f1ae42"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "absolutelib-java-1.2.7-javadoc.jar",
          "url": "absolutelib-java-1.2.7-javadoc.jar",
          "size": 573907,
          "sha512": "86669378521fa36701fcc5be694e98434a6a1c5f8dd004f9fdb051641e1d9688e580af937119cbc833986ec3ce98288415c2c26bdc2ac521bb84962c49e3840c",
          "sha256": "6315c2bcbe9ddf6e4f647216055a872528939be61d614a6a081b6d8221a7f2a7",
          "sha1": "9280b8e1ee0e6e16bdb3df7469b99149272e1eef",
          "md5": "733e09d70825b560cff492b6a30a8322"
        }
      ]
    }
  ]
}
