{
  "formatVersion": "1.1",
  "component": {
    "group": "ca.team4308",
    "module": "absolutelib-java",
    "version": "1.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "absolutelib-java-1.1.7.jar",
          "url": "absolutelib-java-1.1.7.jar",
          "size": 129908,
          "sha512": "da215e6831ac06ef7fd5ef2313b91ff454942c50d7ab3e0af87b240c8e833294ce42ff9277334254485a84240e4793318969276ece2f6b45cac1fc3a596af8e1",
          "sha256": "8064ccd7e8c9ff9ae6883a16aae75531bf7f25f59559f05b2216772594ae0878",
          "sha1": "cfddb1890c2e30cda1160c002859c283b2298203",
          "md5": "350691e859358110f70f57672e41cefa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "api-java",
          "version": {
            "requires": "5.33.1"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "wpiapi-java",
          "version": {
            "requires": "5.33.1"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "25.4.0"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2025.0.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.littletonrobotics.akit",
          "module": "akit-java",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.pathplanner.lib",
          "module": "PathplannerLib-java",
          "version": {
            "requires": "2025.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "absolutelib-java-1.1.7.jar",
          "url": "absolutelib-java-1.1.7.jar",
          "size": 129908,
          "sha512": "da215e6831ac06ef7fd5ef2313b91ff454942c50d7ab3e0af87b240c8e833294ce42ff9277334254485a84240e4793318969276ece2f6b45cac1fc3a596af8e1",
          "sha256": "8064ccd7e8c9ff9ae6883a16aae75531bf7f25f59559f05b2216772594ae0878",
          "sha1": "cfddb1890c2e30cda1160c002859c283b2298203",
          "md5": "350691e859358110f70f57672e41cefa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "absolutelib-java-1.1.7-sources.jar",
          "url": "absolutelib-java-1.1.7-sources.jar",
          "size": 62944,
          "sha512": "ff717c84a5e6a2aedffc18bdfc573b3870c019d7632e2aa8dd28bb14548aae1e1cbed37ccbfa4956ea9cfd259e2dee802fd890bfe52dc8a72b0b98320729c671",
          "sha256": "f005254ce9aec65296d276c082f7c482c3e1556205ed247dab3c42726504e17b",
          "sha1": "e920d0b36065616a17c7b1fab3bd1547360e6372",
          "md5": "348a97f08eeebb40ede1b7f024e23c97"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "absolutelib-java-1.1.7-javadoc.jar",
          "url": "absolutelib-java-1.1.7-javadoc.jar",
          "size": 381530,
          "sha512": "c0b706c64a9653fc2dd39206e86a290b1ea17cf988ae808e869575a85ecd99548d45c3fdc14ff5af832b5eec438bec7055680976d2260d5b5af4b7cf6ca40c3e",
          "sha256": "6dde33c12093fc7abde6846309d0e8e0e044a8721ad45e10fff24c21b45fcd35",
          "sha1": "44338eade939a63700f3665f9dd47deb278cf020",
          "md5": "97da911e83731750332a0abe943fbd74"
        }
      ]
    }
  ]
}
