{
  "formatVersion": "1.1",
  "component": {
    "group": "ca.team4308",
    "module": "absolutelib-java",
    "version": "1.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "absolutelib-java-1.2.4.jar",
          "url": "absolutelib-java-1.2.4.jar",
          "size": 225989,
          "sha512": "ffbe8c78f08f05799a58af13d4e1510cf2a07e02aef8f8f1101f245a3e69bd7ea4a46ad1a694b00b25128f2c7ce5e28ad51edf3a7b834dd8d2b6609217f33eae",
          "sha256": "9d0a4a11cf083f23952f47e555a582a9f124f7dcbd60d237fcc4ee1d91e05da5",
          "sha1": "e815bfcc1508d2ffc1d3e96540b6fa3b678fbcc0",
          "md5": "cd9dc689c8f97459d0bbe32b3383acd2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "api-java",
          "version": {
            "requires": "5.36.0"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "wpiapi-java",
          "version": {
            "requires": "5.36.0"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "26.1.0"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2026.0.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.littletonrobotics.akit",
          "module": "akit-java",
          "version": {
            "requires": "26.0.0"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.pathplanner.lib",
          "module": "PathplannerLib-java",
          "version": {
            "requires": "2026.1.2"
          }
        },
        {
          "group": "org.photonvision",
          "module": "photonlib-java",
          "version": {
            "requires": "v2026.1.1-rc-3"
          }
        },
        {
          "group": "org.photonvision",
          "module": "photontargeting-java",
          "version": {
            "requires": "v2026.1.1-rc-3"
          }
        },
        {
          "group": "swervelib",
          "module": "YAGSL-java",
          "version": {
            "requires": "2026.1.14"
          }
        }
      ],
      "files": [
        {
          "name": "absolutelib-java-1.2.4.jar",
          "url": "absolutelib-java-1.2.4.jar",
          "size": 225989,
          "sha512": "ffbe8c78f08f05799a58af13d4e1510cf2a07e02aef8f8f1101f245a3e69bd7ea4a46ad1a694b00b25128f2c7ce5e28ad51edf3a7b834dd8d2b6609217f33eae",
          "sha256": "9d0a4a11cf083f23952f47e555a582a9f124f7dcbd60d237fcc4ee1d91e05da5",
          "sha1": "e815bfcc1508d2ffc1d3e96540b6fa3b678fbcc0",
          "md5": "cd9dc689c8f97459d0bbe32b3383acd2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "absolutelib-java-1.2.4-sources.jar",
          "url": "absolutelib-java-1.2.4-sources.jar",
          "size": 113438,
          "sha512": "e65d9c056e9afcc573cf585ea643fde54afcc9c96bf877a33e57ade36ef26c42b1e1dbabaa256d39dd1fae4974b35f6f695f9af9e0703e5a7e1429201ed79f72",
          "sha256": "5481061acca5f3f2c6581184d01ca9b8606377e7ffaf686b6d8ef1359ab734bd",
          "sha1": "fe0fea23c859f035b189c685dfd0551b245fd268",
          "md5": "3c39d19e9c25c68b011dd8df77545d0a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "absolutelib-java-1.2.4-javadoc.jar",
          "url": "absolutelib-java-1.2.4-javadoc.jar",
          "size": 573486,
          "sha512": "ecbaabfa545e182d58ccb3f065fabcc97dd7f4909c83808968a4fe3e700c95e108db718948120a365ac27377a99ef8c89feb68d3edf8759cf802c9749b2a8d2e",
          "sha256": "f3f06046323c5ab33ee25a9534d40423a7fcff7dddb9c1c9a6762cc7c9b3ad5c",
          "sha1": "67afbe2c650a10a1b815cf451f4c5e050fe801a2",
          "md5": "2d3eccfe74483f15337cbae6694c5c21"
        }
      ]
    }
  ]
}
