{
  "formatVersion": "1.1",
  "component": {
    "group": "ca.team4308",
    "module": "absolutelib-java",
    "version": "1.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "absolutelib-java-1.1.4.jar",
          "url": "absolutelib-java-1.1.4.jar",
          "size": 126290,
          "sha512": "800ecba103b439e71d678c4036c398e67140bac694c82306ca1b4692188c3e35037c50262b9a3df9158ec40c37688bdd786841e86272346f5f7c8ca665937d59",
          "sha256": "355d3a1672dd25117375fff8f653cc501c2dab37977665a49554edee48d5e02a",
          "sha1": "d5c7943bb3fc806e8f11f2aae953938e32af17ef",
          "md5": "d88bd0c4486f604477bcee1f238d4d85"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2025.1.1"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "api-java",
          "version": {
            "requires": "5.33.1"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "wpiapi-java",
          "version": {
            "requires": "5.33.1"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "25.4.0"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2025.0.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.littletonrobotics.akit",
          "module": "akit-java",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.pathplanner.lib",
          "module": "PathplannerLib-java",
          "version": {
            "requires": "2025.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "absolutelib-java-1.1.4.jar",
          "url": "absolutelib-java-1.1.4.jar",
          "size": 126290,
          "sha512": "800ecba103b439e71d678c4036c398e67140bac694c82306ca1b4692188c3e35037c50262b9a3df9158ec40c37688bdd786841e86272346f5f7c8ca665937d59",
          "sha256": "355d3a1672dd25117375fff8f653cc501c2dab37977665a49554edee48d5e02a",
          "sha1": "d5c7943bb3fc806e8f11f2aae953938e32af17ef",
          "md5": "d88bd0c4486f604477bcee1f238d4d85"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "absolutelib-java-1.1.4-sources.jar",
          "url": "absolutelib-java-1.1.4-sources.jar",
          "size": 62666,
          "sha512": "614d7bda48d62dcfe330ba049b0ba6cd108467a8dbb78689f372830d548d912f17a466c24c3ee18a458b28eb2572f41cdcb91d91be2ff08c70c486c0c64f15da",
          "sha256": "994cbdcb776b8dcc7e68758f0da168b52f793b9ca2b61cea6d8d5ea7ec2999ae",
          "sha1": "769b5f8e0ac3ff0f6c4b2deeb6a8cd13992c0eb3",
          "md5": "0974823fb6ac0f7498ed512de50161ef"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "absolutelib-java-1.1.4-javadoc.jar",
          "url": "absolutelib-java-1.1.4-javadoc.jar",
          "size": 378509,
          "sha512": "73d67135da0f609163bb993cad62238296087be5eec29ce16ab353ade3b053c2c9efe2d87c4c77d386d4fe58c67a039ceb49095067806529529de8b091498660",
          "sha256": "3d683f74277c46384267ff2df96b80d9c1d2233e1824730defbb8ecbd84c03a7",
          "sha1": "c63d5c1cafe07f3c834a125db91d25de3b526996",
          "md5": "12b21652ec4fe20feb8a2cf37a96683e"
        }
      ]
    }
  ]
}
